import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import localFont from 'next/font/local'
import Navbar from './Navbar'
import { Suspense } from 'react'
const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'] })
const sans = localFont({
  src: '../public/fonts/iransans/fonts.woff2',
  variable: '--font-sans'
})
import AuthProvider from './auth/Provider'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={sans.variable}>
        <AuthProvider>
          <Navbar />
          <main className='p-5'>
            <Suspense fallback={<p>loading...</p>}>{children}</Suspense>
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
